### ISSUE TITLE
EMD crash when user cost function is used

### ISSUE THREAD

**Issue by YanaiA** [kyamagu/mexopencv#191]
for Earth Mover's Distance, openCV crashes if there is a user cost function and the lowerBound is expected as output.

My suggestion: replace 
    double d = EMD(signature1, signature2, distType, cost, &lowerBound, flow);

with:
    double d;
    if (distType==cv::DIST_USER	)
    {
        d = EMD(signature1, signature2, distType, cost);
    }
    else
    {
        d = EMD(signature1, signature2, distType, cost, &lowerBound, flow);
    }

**Comment by amroamroamro** [comment]
thanks @YanaiA 
How about the following, this way `flow` can still be computed (if requested):

```cpp
if (distType==cv::DIST_USER && cost.empty())
    mexErrMsgIdAndTxt("mexopencv:error",
        "In case of user-defined distance, cost matrix must be defined");

// Process
Mat signature1(rhs[0].toMat(CV_32F)),
    signature2(rhs[1].toMat(CV_32F)),
    flow;
float emd = EMD(signature1, signature2, distType, cost,
    (nlhs>1 && cost.empty() ? &lowerBound : NULL),
    (nlhs>2 ? flow : noArray()));
plhs[0] = MxArray(emd);
if (nlhs>1)
    plhs[1] = MxArray(lowerBound);
if (nlhs>2)
    plhs[2] = MxArray(flow);
```

I'm already working on updating a number of functions, so I'll include this in my next pull request :)

**Comment by YanaiA** [comment]
@amroamroamro sounds great!
Thanks

**Comment by kyamagu** [comment]
@YanaiA Thanks for your pull request. I've merged the request to v2.4 branch, but leave it from v3.0 for now since @amroamroamro seems to have a number of updates.

**Comment by amroamroamro** [comment]
sorry it took me so long to push my updates. Here's the PR #198 

I still have some more changes for later when they're ready. I added new modules like: shape, superres, stitching, videostab.

**Comment by YanaiA** [comment]
@amroamroamro Thanks for the update. Can you please merge it to 2.4 branch too?

**Comment by amroamroamro** [comment]
@YanaiA  what the whole thing? I'm afraid it's not that easy :) The two branches have gotten so far apart, and it would be difficult to backport and pick only the 2.4 compatible things...

I strongly suggest you move to 3.0, that's where all the development is happening in OpenCV!

**Comment by YanaiA** [comment]
Specifically I meant just the EMD changes.
version 3.0 has its own issues (
https://github.com/kyamagu/mexopencv/issues/195)
